In [1]:
import numpy as np

In [2]:
#takes sclers also
def sigmoid(arr):
    return 1/(1 + np.exp(-arr))

def dsigmoid(ele):
    return   sigmoid(ele) *(1 - sigmoid(ele))

In [3]:
alpha = 0.3

In [4]:
#one layer 
#2 neurons
# 2 inputs
#2 outputs
#for now let our l be sum of 2 y's
#for now ignore the bias

inputs = np.array([3,4]).reshape(2,1)
weights = np.random.random(4).reshape(2,2)  #each row one neuron

In [5]:
#forward pass
inter_outputs =  weights @ inputs #shape = 2,1 
outputs = sigmoid(inter_outputs)
l = np.prod(outputs)
print("loss:",l)

#---------------------------
#udate weights ==>>
#trying to represent them as jacobains instead of gradinets or partial derivatives XD
dl_dy = np.array([ outputs[1, 0], outputs[0, 0] ]).reshape(1,2)
dy_dz = np.array([ [dsigmoid(inter_outputs[0, 0]), 0], [0, dsigmoid(inter_outputs[1, 0]) ] ]) #shae = 2,2
dz_dw = np.array([[inputs[0,0], inputs[1,0], 0, 0], [0, 0, inputs[0,0], inputs[1,0]] ]) # shape 2,4
#---------------------
# print(dl_dy)
# print("---------")
# print(dy_dz)
# print("---------")
# print(dz_dw)
#----------------------------------------
dl_dw = dl_dy  @ dy_dz @ dz_dw
print("dl_dw:" ,dl_dw)

#--------------------
#update weights
flattend_weights = weights.ravel() # this returns view so original weights will get updated, but doesn't matter here anyhow
flattend_weights = flattend_weights - (alpha * dl_dw.ravel())
weights = flattend_weights.reshape(2,2)
#--------------------------------
print( "weights:", weights)

loss: 0.7163938090928773
dl_dw: [[0.59338612 0.7911815  0.022289   0.02971867]]
weights: [[-0.16953402 -0.0027416 ]
 [ 0.30640333  0.89584788]]


In [6]:
#backprop or wight update here is not directly related to with loss value itself
#like we are not using that specific l value to update any but we needed many intermediate
#vlaues produced in that specific forwad pass


In [7]:
import torch

In [ ]:
Y = torch.tensor([[1], [0]], dtype=torch.float64)
W = torch.rand((2, 3), dtype=torch.float64, requires_grad=True)
X = torch.tensor([[1,0], [0,1]], dtype=torch.float64)
B = torch.tensor([0, 0, 0], dtype = torch.float64).resize_(1, 3); B.requires_grad = True

In [2073]:
Z = X @ W + B
A = torch.sigmoid(Z)
Yhat = torch.sum(A, dim=1, keepdim=True)
L = torch.square(Y - Yhat).sum(dim = 0, keepdim = True) * 1/X.shape[0]
print(Yhat)
print(L)
L.backward()
print(W.grad)
print(B.grad)
with torch.no_grad():
    W -= 0.01 * W
    B -= 0.01 * B

tensor([[1.5000],
        [1.5000]], dtype=torch.float64, grad_fn=<SumBackward1>)
tensor([[1.2500]], dtype=torch.float64, grad_fn=<DivBackward0>)
tensor([[173.5503, 174.7427, 173.1019],
        [501.3947, 497.8843, 501.7938]], dtype=torch.float64)
tensor([[674.9451, 672.6270, 674.8957]], dtype=torch.float64)


In [118]:
print(L)

tensor([[2.3283]], dtype=torch.float64, grad_fn=<DivBackward0>)
