In [26]:
import numpy as np

In [27]:
#takes sclers also
def sigmoid(arr):
    return 1/(1 + np.exp(-arr))

def dsigmoid(ele):
    return   sigmoid(ele) *(1 - sigmoid(ele))

In [28]:
alpha = 0.3

In [29]:
#one layer 
#2 neurons
# 2 inputs
#2 outputs
#for now let our l be sum of 2 y's
#for now ignore the bias

inputs = np.array([3,4]).reshape(2,1)
weights = np.random.random(4).reshape(2,2)  #each row one neuron

In [30]:
#forward pass
inter_outputs =  weights @ inputs #shape = 2,1 
outputs = sigmoid(inter_outputs)
l = np.prod(outputs)
print("loss:",l)

#---------------------------
#udate weights ==>>
#trying to represent them as jacobains instead of gradinets or partial derivatives XD
dl_dy = np.array([ outputs[1, 0], outputs[0, 0] ]).reshape(1,2)
dy_dz = np.array([ [dsigmoid(inter_outputs[0, 0]), 0], [0, dsigmoid(inter_outputs[1, 0]) ] ]) #shae = 2,2
dz_dw = np.array([[inputs[0,0], inputs[1,0], 0, 0], [0, 0, inputs[0,0], inputs[1,0]] ]) # shape 2,4
#---------------------
# print(dl_dy)
# print("---------")
# print(dy_dz)
# print("---------")
# print(dz_dw)
#----------------------------------------
dl_dw = dl_dy  @ dy_dz @ dz_dw
print("dl_dw:" ,dl_dw)

#--------------------
#update weights
flattend_weights = weights.ravel() # this returns view so original weights will get updated, but doesn't matter here anyhow
flattend_weights = flattend_weights - (alpha * dl_dw.ravel())
weights = flattend_weights.reshape(2,2)
#--------------------------------
print( "weights:", weights)

loss: 0.8474612404511427
dl_dw: [[0.24718766 0.32958355 0.15576934 0.20769245]]
weights: [[0.1067591  0.32254482]
 [0.71749901 0.04683359]]


In [31]:
#backprop or wight update here is not directly related to with loss value itself
#like we are not using that specific l value to update any but we needed many intermediate
#vlaues produced in that specific forwad pass


In [32]:
np.random.randn(64,10)

array([[ 1.65126083e+00, -1.37689405e+00, -2.78370183e-01,
        -9.51808972e-01,  4.53246145e-01, -4.06277130e-01,
         4.09409235e-01,  1.37970407e-01,  2.11712205e+00,
         1.73684171e+00],
       [ 4.42785705e-01,  7.33002607e-01,  2.44578723e+00,
         4.56889022e-01, -9.69619734e-01,  1.33069654e-01,
        -1.60152559e-01, -2.75629149e-02,  7.66143382e-01,
        -1.47143874e+00],
       [ 1.51364559e-01,  9.34847609e-01,  1.73226110e-01,
        -1.29304934e+00,  3.57849426e-01, -5.91850742e-02,
        -5.90865930e-02,  1.22776215e+00, -1.22833256e+00,
        -5.83177479e-01],
       [ 4.57308984e-01, -2.44111758e-02,  7.44878539e-01,
         1.64336202e+00,  1.25931943e+00, -1.43934266e-01,
        -7.49697673e-01,  6.36139935e-01,  1.52671343e+00,
         4.58944871e-03],
       [-5.90361664e-02, -1.68720734e+00,  2.59791451e+00,
        -9.62035894e-01, -9.63493373e-01,  8.70595016e-01,
        -3.57002293e-01, -4.20613912e-01,  3.39631484e-01,
         7.

In [33]:
x = np.random.random(20)

In [34]:
x

array([0.59447329, 0.87120529, 0.27416489, 0.40473737, 0.24271199,
       0.95455683, 0.43217223, 0.59506932, 0.25250243, 0.35368886,
       0.74440368, 0.16441374, 0.97937836, 0.89877854, 0.76453542,
       0.61543452, 0.51310656, 0.89615692, 0.40535613, 0.45279926])

In [35]:
words = open("scratchpad.txt", "r").read().splitlines()

In [36]:
l = [1,2,3]
# l.x = "hai"
print(dir(l))
# print(vars(l))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [37]:
vars(list)

mappingproxy({'__new__': <function list.__new__(*args, **kwargs)>,
              '__repr__': <slot wrapper '__repr__' of 'list' objects>,
              '__hash__': None,
              '__getattribute__': <slot wrapper '__getattribute__' of 'list' objects>,
              '__lt__': <slot wrapper '__lt__' of 'list' objects>,
              '__le__': <slot wrapper '__le__' of 'list' objects>,
              '__eq__': <slot wrapper '__eq__' of 'list' objects>,
              '__ne__': <slot wrapper '__ne__' of 'list' objects>,
              '__gt__': <slot wrapper '__gt__' of 'list' objects>,
              '__ge__': <slot wrapper '__ge__' of 'list' objects>,
              '__iter__': <slot wrapper '__iter__' of 'list' objects>,
              '__init__': <slot wrapper '__init__' of 'list' objects>,
              '__len__': <slot wrapper '__len__' of 'list' objects>,
              '__getitem__': <method '__getitem__' of 'list' objects>,
              '__setitem__': <slot wrapper '__setitem__' of

In [38]:
import numpy as np

In [39]:
print(np.ndarray)
x = np.ndarray((1,2))
vars(np.ndarray)


<class 'numpy.ndarray'>


mappingproxy({'__new__': <function ndarray.__new__(*args, **kwargs)>,
              '__repr__': <slot wrapper '__repr__' of 'numpy.ndarray' objects>,
              '__str__': <slot wrapper '__str__' of 'numpy.ndarray' objects>,
              '__lt__': <slot wrapper '__lt__' of 'numpy.ndarray' objects>,
              '__le__': <slot wrapper '__le__' of 'numpy.ndarray' objects>,
              '__eq__': <slot wrapper '__eq__' of 'numpy.ndarray' objects>,
              '__ne__': <slot wrapper '__ne__' of 'numpy.ndarray' objects>,
              '__gt__': <slot wrapper '__gt__' of 'numpy.ndarray' objects>,
              '__ge__': <slot wrapper '__ge__' of 'numpy.ndarray' objects>,
              '__iter__': <slot wrapper '__iter__' of 'numpy.ndarray' objects>,
              '__buffer__': <slot wrapper '__buffer__' of 'numpy.ndarray' objects>,
              '__add__': <slot wrapper '__add__' of 'numpy.ndarray' objects>,
              '__radd__': <slot wrapper '__radd__' of 'numpy.ndarray' obje

In [40]:
np.exp(x)

array([[1.08588561, 1.05329476]])

In [41]:
print("hai") if False else print("hello")

hello


In [42]:
import torch

In [68]:
t = torch.tensor([1,2], dtype = torch.float32, requires_grad= True)

In [69]:
t[0] = 3

RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

In [70]:
t

tensor([1., 2.], requires_grad=True)

In [71]:
t.sin_()

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

In [72]:
type(t.data)

torch.Tensor

In [73]:
type(t)

torch.Tensor

In [74]:
type(t.grad)

NoneType

In [84]:
x = (3*t + 5).mean()

In [85]:
x

tensor(9.5000, grad_fn=<MeanBackward0>)

In [86]:
x.backward()

In [87]:
t.grad

tensor([1.5000, 1.5000])

In [88]:
t

tensor([1., 2.], requires_grad=True)